import dImg from './uploads/d.png';
import eImg from './uploads/e.png';
import rImg from './uploads/r.png';
import zImg from './uploads/z.png';

export const PROJECTS = [
  {
    id: 'aether-db',
    title: 'Aether Cache',
    category: 'backend',
    role: 'Distributed Storage Engine',
    desc: 'An ultra-low latency caching server designed for distributed cluster caching, fast serialized lookups, and multi-threaded data validation.',
    tech: ['Rust', 'gRPC', 'Protobuf', 'Docker'],
    metrics: { label: 'READ LATENCY', value: '0.45 ms' },
    status: 'Active',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'helios-ui',
    title: 'Helios Carbon',
    category: 'frontend',
    role: 'Interactive Component Framework',
    desc: 'Premium design tokens mapped to fluid CSS compilers. Offers native layout-shift prevention, zero sub-pixel rounding errors, and custom layout controllers.',
    tech: ['Vite', 'React', 'Tailwind CSS', 'TypeScript'],
    metrics: { label: 'HYDRATION RATE', value: '1.2 ms' },
    status: 'Stable V2',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'apex-docs',
    title: 'Apex Archiver',
    category: 'compliance',
    role: 'Compliance & Verification Suite',
    desc: 'State-of-the-art secure compiler matching regulatory standards, auto-generating compliance checklists and operational planning documents.',
    tech: ['PostgreSQL', 'Secure Crypt', 'Markdown AST', 'OAuth2'],
    metrics: { label: 'ACCURACY SCORE', value: '99.98% QA' },
    status: 'Ready',
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'chrono-ledger',
    title: 'Chrono Ledger',
    category: 'backend',
    role: 'Time-Series Shards Engine',
    desc: 'A write-ahead-logging (WAL) based ledger designed for high-throughput IoT time-series events and predictive query resolution.',
    tech: ['Go', 'gRPC', 'InfluxDB', 'Kubernetes'],
    metrics: { label: 'WRITE SPAN', value: '0.28 ms' },
    status: 'Production',
    image: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'vespera-webglow',
    title: 'Vespera WebGlow',
    category: 'frontend',
    role: 'WebGL Presentation Core',
    desc: 'A specialized WebGL framework combining hardware-accelerated shaders with responsive vector bounding containers for fluid layouts.',
    tech: ['Three.js', 'Vite', 'GLSL', 'React'],
    metrics: { label: 'RENDER TIME', value: '1.05 ms' },
    status: 'Active V4',
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'cipher-guardian',
    title: 'Cipher Guardian',
    category: 'compliance',
    role: 'Decentralized HSM Rotator',
    desc: 'Automated cryptographic key rotation daemon matching FIPS 140-3 operational guidelines and multi-tenant workspace integration.',
    tech: ['Python', 'Vault', 'OpenSSL', 'Terraform'],
    metrics: { label: 'SECURE MARGIN', value: '99.999%' },
    status: 'Certified',
    image: 'https://images.unsplash.com/photo-1633265486064-086b219458ec?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'nova-mesh',
    title: 'Nova Mesh',
    category: 'backend',
    role: 'P2P Cluster Orchestrator',
    desc: 'A high-integrity service mesh providing autonomous healthchecks, sidecar telemetry, and instant node-to-node routing protocols.',
    tech: ['C++', 'eBPF', 'Docker', 'Consul'],
    metrics: { label: 'CONCURRENCY', value: '4.2M req/s' },
    status: 'Beta-V1',
    image: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'stratum-glass',
    title: 'Stratum Glass',
    category: 'frontend',
    role: 'Sub-pixel Glass-morphic UI Componentry',
    desc: 'Hardware-composited theme elements mapped to adaptive backdrop filters, completely avoiding redraw issues on complex scrolls.',
    tech: ['Sass', 'Tailwind CSS', 'Vite', 'Framer Motion'],
    metrics: { label: 'LAYOUT LATENCY', value: '0.8 ms' },
    status: 'Stable',
    image: 'https://images.unsplash.com/photo-1618005198143-e52834658512?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'aegis-sentinel',
    title: 'Aegis Sentinel',
    category: 'compliance',
    role: 'SOC2 Continuous Auditing Framework',
    desc: 'Continuous non-invasive policy evaluator validating active server configurations and user credentials under strict SOC2 rulesets.',
    tech: ['Docker', 'OPA Rego', 'AWS IAM', 'Node.js'],
    metrics: { label: 'SCAN SPEED', value: '2.4s Full' },
    status: 'Live Tool',
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'hydra-gateway',
    title: 'Hydra Gateway',
    category: 'backend',
    role: 'Async API Protocol Router',
    desc: 'Hyper-scalable proxy forwarding HTTP/3 and WebSockets with zero-copy stream processing and runtime connection throttling.',
    tech: ['Rust', 'Tokio', 'Quic', 'Redis'],
    metrics: { label: 'THROUGHPUT', value: '85 Gb/s' },
    status: 'Production',
    image: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'lumen-canvas',
    title: 'Lumen Canvas',
    category: 'frontend',
    role: 'Collaborative Vector Editor Engine',
    desc: 'A high-perf vector render pipeline utilizing local space matrix calculations, customized DOM wrappers, and compressed state diffing.',
    tech: ['TypeScript', 'HTML5 Canvas', 'WebAssembly', 'React'],
    metrics: { label: 'FPS STABILITY', value: '120 Hz' },
    status: 'Stable',
    image: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'veritas-ledger',
    title: 'Veritas Ledger',
    category: 'compliance',
    role: 'Immutable Cryptographic Proof Logger',
    desc: 'A Merkelized binary tree database auditing system file system actions and outputting verifiable proofs for standard system events.',
    tech: ['Rust', 'SHA3-256', 'WebAssembly', 'PostgreSQL'],
    metrics: { label: 'PROOF DURATION', value: '4 ms/file' },
    status: 'Active',
    image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'kratos-queue',
    title: 'Kratos Queue',
    category: 'backend',
    role: 'Partitioned Event Broker Shards',
    desc: 'Highly optimized flash-storage broker providing strict sequential message buffering with automated SSD block write coordination.',
    tech: ['C#', 'SQL Server', 'RocksDB', 'Docker'],
    metrics: { label: 'PERSIST RUNTIME', value: '0.92 ms' },
    status: 'Operational',
    image: 'https://images.unsplash.com/photo-1600132806370-bf17e65e942f?auto=format&fit=crop&w=600&q=80',
  }
];

export const IMAGES = [
  {
    src: dImg,
    name: 'RANDEL',
    role: 'Frontend Developer',
    statement: 'I design and implement responsive, high-fidelity user interfaces. My core focus is on smooth interactions, pixel-level layouts, and robust React frontend structures.',
    bg: '#F4845F',
    panel: '#F79B7F',
  },
  {
    src: zImg,
    name: 'GRAZIELLE',
    role: 'Researcher & Operations',
    statement: 'I lead market research, manage operational pipelines, and handle all regulatory paper works to ensure structural clarity and seamless execution of our designs.',
    bg: '#6BBF7A',
    panel: '#85CC92',
  },
  {
    src: rImg,
    name: 'RENZ MARTIN',
    role: 'Frontend Developer',
    statement: 'I build reactive, visually immersive digital ecosystems. My love is merging futuristic aesthetics with clean, modular, and performance-tuned code.',
    bg: '#E82B2B',
    panel: '#E82B2B',
  },
  {
    src: eImg,
    name: 'ELIJAH BOON',
    role: 'Backend Developer',
    statement: 'I architect secure and scalable backend logic, database integrations, and high-performance server APIs to sustain heavy user traffic behind the scenes.',
    bg: '#6EB5FF',
    panel: '#8DC4FF',
  },
];
