import dImg from './uploads/d.png';
import eImg from './uploads/e.png';
import rImg from './uploads/r.png';
import zImg from './uploads/z.png';

export const PROJECTS = [
  {
    id: 0,
    num: '01',
    category: 'backend',
    tag: 'Backend // Production',
    status: 'live',
    title: 'Chrono Ledger',
    desc: 'Write-ahead-logging ledger for high-throughput IoT time-series events with predictive query caching and sub-millisecond read latency targets.',
    tech: ['Rust', 'gRPC', 'Redis', 'WAL'],
    featured: true,
    metrics: [
      { value: '<2ms', label: 'Read Latency' },
      { value: '99.97%', label: 'Uptime' },
      { value: '40k/s', label: 'Events/sec' },
    ],
    expandDesc: 'Built for burst I/O from thousands of IoT edge nodes. Uses a custom WAL engine with predictive cache warming to replace traditional RDBMS bottlenecks in real-time sensor pipelines. Designed by the Frey backend team.',
  },
  {
    id: 1,
    num: '02',
    category: 'compliance',
    tag: 'Compliance // Certified',
    status: 'certified',
    title: 'Cipher Guardian',
    desc: 'Cryptographic key rotation daemon matching FIPS 140-3 guidelines with multi-tenant workspace isolation.',
    tech: ['NIST', 'AES-256', 'Daemon'],
    featured: false,
    metrics: [
      { value: 'FIPS', label: 'Certified' },
      { value: '0', label: 'Key Leaks' },
      { value: '24/7', label: 'Monitoring' },
    ],
    expandDesc: 'Enterprise-grade key rotation daemon built to FIPS 140-3 spec. Automates cryptographic lifecycle management across multi-tenant workspaces. Verified and audited by Frey R&O.',
  },
  {
    id: 2,
    num: '03',
    category: 'frontend',
    tag: 'Frontend // Active V4',
    status: 'active',
    title: 'Vespera WebGlow',
    desc: 'WebGL framework combining hardware-accelerated shaders with responsive vector bounding containers for pixel-perfect rendering.',
    tech: ['WebGL', 'GLSL', 'React'],
    featured: false,
    metrics: [
      { value: '60fps', label: 'Target FPS' },
      { value: '3.2kb', label: 'Runtime' },
      { value: 'V4', label: 'Build' },
    ],
    expandDesc: 'GPU-first rendering framework bringing GLSL shader power into standard React component trees. Enables pixel-accurate visual design without sacrificing responsiveness. Built for the Frey frontend practice.',
  },
  {
    id: 3,
    num: '04',
    category: 'frontend',
    tag: 'Frontend // Beta',
    status: 'active',
    title: 'Nexus Workflow',
    desc: 'AI-native task orchestration layer with real-time pipeline visualization and automated trigger scheduling.',
    tech: ['Python', 'LangChain', 'GPT-4o'],
    featured: false,
    metrics: [
      { value: '12+', label: 'Integrations' },
      { value: 'Beta', label: 'Status' },
      { value: 'GPT-4o', label: 'Backbone' },
    ],
    expandDesc: "AI-native orchestration connecting LLM reasoning with external API triggers. Enables complex automation through Frey's AI practice with a visual pipeline canvas.",
  },
  {
    id: 4,
    num: '05',
    category: 'backend',
    tag: 'Backend // Research',
    status: 'research',
    title: 'Pulse Grid',
    desc: 'Distributed sensor mesh with adaptive polling and anomaly flagging across low-power microcontroller nodes.',
    tech: ['C++', 'MQTT', 'ESP32'],
    featured: false,
    metrics: [
      { value: '128', label: 'Max Nodes' },
      { value: '18mA', label: 'Avg Draw' },
      { value: 'ESP32', label: 'Target MCU' },
    ],
    expandDesc: 'Distributed sensor mesh protocol for low-power MCU networks. Implements adaptive polling with onboard anomaly detection, cutting cloud telemetry overhead. Core Frey embedded research project.',
  },
  {
    id: 0, // We can use unique IDs. Let's make IDs sequential: 5, 6, 7, 8
    id: 5,
    num: '06',
    category: 'compliance',
    tag: 'Compliance // Audited',
    status: 'live',
    title: 'Aegis Sentinel',
    desc: 'Continuous non-invasive policy evaluator validating active server configurations and user credentials under strict SOC2 rulesets.',
    tech: ['Docker', 'OPA Rego', 'AWS IAM'],
    featured: false,
    metrics: [
      { value: '2.4s', label: 'Scan Time' },
      { value: 'SOC2', label: 'Compliance' },
      { value: '100%', label: 'Coverage' },
    ],
    expandDesc: 'Continuous configuration auditing daemon running non-invasive compliance verification scans across federated container runtimes.',
  },
  {
    id: 6,
    num: '07',
    category: 'backend',
    tag: 'Backend // Active',
    status: 'live',
    title: 'Hydra Gateway',
    desc: 'Hyper-scalable proxy forwarding HTTP/3 and WebSockets with zero-copy stream processing and runtime connection throttling.',
    tech: ['Rust', 'Tokio', 'QUIC'],
    featured: false,
    metrics: [
      { value: '85Gb/s', label: 'Throughput' },
      { value: '0-copy', label: 'Forwarding' },
      { value: 'QUIC', label: 'Protocol' },
    ],
    expandDesc: 'High-throughput stream proxy optimized for gRPC and WebSocket streams, featuring low latency memory mapping and flow control.',
  },
  {
    id: 7,
    num: '08',
    category: 'frontend',
    tag: 'Frontend // Production',
    status: 'active',
    title: 'Lumen Canvas',
    desc: 'A high-performance vector render pipeline utilizing local space matrix calculations and compressed state diffing.',
    tech: ['TypeScript', 'Wasm', 'Canvas'],
    featured: false,
    metrics: [
      { value: '120Hz', label: 'Refresh Rate' },
      { value: 'Wasm', label: 'Core Engine' },
      { value: '<1ms', label: 'Frame Time' },
    ],
    expandDesc: 'WebAssembly-powered vector rendering engine for high-frequency interactive canvas applications and multi-user drawing environments.',
  },
];

export const IMAGES = [
  {
    src: dImg,
    name: 'RANDEL',
    role: 'Frontend Developer',
    statement: 'I design and implement responsive, high-fidelity user interfaces. My core focus is on smooth interactions, pixel-level layouts, and robust React frontend structures.',
    bg: '#F4845F',
    panel: '#F79B7F',
  },
  {
    src: zImg,
    name: 'GRAZIELLE',
    role: 'Researcher & Operations',
    statement: 'I lead market research, manage operational pipelines, and handle all regulatory paper works to ensure structural clarity and seamless execution of our designs.',
    bg: '#6BBF7A',
    panel: '#85CC92',
  },
  {
    src: rImg,
    name: 'RENZ MARTIN',
    role: 'Frontend Developer',
    statement: 'I build reactive, visually immersive digital ecosystems. My love is merging futuristic aesthetics with clean, modular, and performance-tuned code.',
    bg: '#E82B2B',
    panel: '#E82B2B',
  },
  {
    src: eImg,
    name: 'ELIJAH BOON',
    role: 'Backend Developer',
    statement: 'I architect secure and scalable backend logic, database integrations, and high-performance server APIs to sustain heavy user traffic behind the scenes.',
    bg: '#6EB5FF',
    panel: '#8DC4FF',
  },
];
